version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: '09:00'
      timezone: America/Mexico_City
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - automated
    commit-message:
      prefix: chore
      include: scope
    reviewers:
      - carlostoek