"""add_low_stock_threshold

Revision ID: 41d674ac4f9a
Revises: 499b5924723f
Create Date: 2026-04-05 14:18:42.884560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d674ac4f9a'
down_revision: Union[str, None] = '499b5924723f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('low_stock_threshold', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_products', schema=None) as batch_op:
        batch_op.drop_column('low_stock_threshold')

    # ### end Alembic commands ###
