"""add vip entry status and stage to users

Revision ID: 9fab8787057e
Revises: e8de5494e5b6
Create Date: 2026-03-31 15:15:37.921271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fab8787057e'
down_revision: Union[str, None] = 'e8de5494e5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vip_entry_status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('vip_entry_stage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vip_entry_stage')
    op.drop_column('users', 'vip_entry_status')
    # ### end Alembic commands ###
