"""add selected_emoji_ids to broadcast_messages

Revision ID: add_selected_emoji_ids
Revises: 287e36271be4
Create Date: 2026-04-03 02:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_selected_emoji_ids'
down_revision: Union[str, None] = '287e36271be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcast_messages', sa.Column('selected_emoji_ids', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcast_messages', 'selected_emoji_ids')
    # ### end Alembic commands ###