"""initial schema baseline

Revision ID: e8de5494e5b6
Revises: 
Create Date: 2026-03-30 09:51:56.826600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8de5494e5b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archetypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archetype_type', sa.Enum('SEDUCTOR', 'OBSERVER', 'DEVOTO', 'EXPLORADOR', 'MISTERIOSO', 'INTREPIDO', name='archetypetype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('traits', sa.Text(), nullable=True),
    sa.Column('unlock_description', sa.Text(), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('archetype_type')
    )
    op.create_index(op.f('ix_archetypes_id'), 'archetypes', ['id'], unique=False)
    op.create_table('besito_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('total_earned', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_besito_balances_id'), 'besito_balances', ['id'], unique=False)
    op.create_index(op.f('ix_besito_balances_user_id'), 'besito_balances', ['user_id'], unique=True)
    op.create_table('blocked_promotion_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('blocked_by', sa.BigInteger(), nullable=True),
    sa.Column('blocked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_permanent', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_promotion_users_id'), 'blocked_promotion_users', ['id'], unique=False)
    op.create_index(op.f('ix_blocked_promotion_users_user_id'), 'blocked_promotion_users', ['user_id'], unique=True)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_name', sa.String(length=200), nullable=True),
    sa.Column('channel_type', sa.Enum('FREE', 'VIP', name='channeltype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('wait_time_minutes', sa.Integer(), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('approval_message', sa.Text(), nullable=True),
    sa.Column('invite_link', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_channel_id'), 'channels', ['channel_id'], unique=True)
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_table('daily_gift_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('besitos_received', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_gift_claims_id'), 'daily_gift_claims', ['id'], unique=False)
    op.create_index(op.f('ix_daily_gift_claims_user_id'), 'daily_gift_claims', ['user_id'], unique=False)
    op.create_table('daily_gift_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('besito_amount', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_gift_config_id'), 'daily_gift_config', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('store_stock', sa.Integer(), nullable=True),
    sa.Column('reward_stock', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_id'), 'packages', ['id'], unique=False)
    op.create_table('reaction_emojis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('besito_value', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emoji')
    )
    op.create_index(op.f('ix_reaction_emojis_id'), 'reaction_emojis', ['id'], unique=False)
    op.create_table('story_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('node_type', sa.Enum('NARRATIVE', 'DECISION', 'ENDING', 'QUIZ', name='nodetype'), nullable=True),
    sa.Column('required_archetype', sa.Enum('SEDUCTOR', 'OBSERVER', 'DEVOTO', 'EXPLORADOR', 'MISTERIOSO', 'INTREPIDO', name='archetypetype'), nullable=True),
    sa.Column('required_vip', sa.Boolean(), nullable=True),
    sa.Column('cost_besitos', sa.Integer(), nullable=True),
    sa.Column('chapter', sa.Integer(), nullable=True),
    sa.Column('order_in_chapter', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_starting_node', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_nodes_id'), 'story_nodes', ['id'], unique=False)
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_id'), 'tariffs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('besito_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CREDIT', 'DEBIT', name='transactiontype'), nullable=False),
    sa.Column('source', sa.Enum('REACTION', 'DAILY_GIFT', 'MISSION', 'PURCHASE', 'ADMIN', name='transactionsource'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['besito_balances.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_besito_transactions_id'), 'besito_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_besito_transactions_user_id'), 'besito_transactions', ['user_id'], unique=False)
    op.create_table('broadcast_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('has_attachment', sa.Boolean(), nullable=True),
    sa.Column('attachment_type', sa.String(length=50), nullable=True),
    sa.Column('attachment_file_id', sa.String(length=500), nullable=True),
    sa.Column('has_reactions', sa.Boolean(), nullable=True),
    sa.Column('is_protected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_messages_id'), 'broadcast_messages', ['id'], unique=False)
    op.create_index(op.f('ix_broadcast_messages_message_id'), 'broadcast_messages', ['message_id'], unique=False)
    op.create_table('package_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_files_id'), 'package_files', ['id'], unique=False)
    op.create_index(op.f('ix_package_files_package_id'), 'package_files', ['package_id'], unique=False)
    op.create_table('pending_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('scheduled_approval_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_requests_id'), 'pending_requests', ['id'], unique=False)
    op.create_index(op.f('ix_pending_requests_user_id'), 'pending_requests', ['user_id'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('price_mxn', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'EXPIRED', name='promotionstatus'), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_id'), 'promotions', ['id'], unique=False)
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reward_type', sa.Enum('BESITOS', 'PACKAGE', 'VIP_ACCESS', name='rewardtype'), nullable=False),
    sa.Column('besito_amount', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('tariff_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_id'), 'rewards', ['id'], unique=False)
    op.create_table('store_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_products_id'), 'store_products', ['id'], unique=False)
    op.create_table('story_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_node_id', sa.Integer(), nullable=True),
    sa.Column('required_archetype', sa.Enum('SEDUCTOR', 'OBSERVER', 'DEVOTO', 'EXPLORADOR', 'MISTERIOSO', 'INTREPIDO', name='archetypetype'), nullable=True),
    sa.Column('required_chapter', sa.Integer(), nullable=True),
    sa.Column('reward_besitos', sa.Integer(), nullable=True),
    sa.Column('reward_package_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['required_node_id'], ['story_nodes.id'], ),
    sa.ForeignKeyConstraint(['reward_package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_achievements_id'), 'story_achievements', ['id'], unique=False)
    op.create_table('story_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('next_node_id', sa.Integer(), nullable=True),
    sa.Column('choice_archetype', sa.Enum('SEDUCTOR', 'OBSERVER', 'DEVOTO', 'EXPLORADOR', 'MISTERIOSO', 'INTREPIDO', name='archetypetype'), nullable=True),
    sa.Column('archetype_points', sa.Integer(), nullable=True),
    sa.Column('additional_cost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_node_id'], ['story_nodes.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['story_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_choices_id'), 'story_choices', ['id'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_code', sa.String(length=64), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'EXPIRED', name='tokenstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['redeemed_by_id'], ['users.telegram_id'], ),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.create_index(op.f('ix_tokens_token_code'), 'tokens', ['token_code'], unique=True)
    op.create_table('user_story_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('current_node_id', sa.Integer(), nullable=True),
    sa.Column('archetype', sa.Enum('SEDUCTOR', 'OBSERVER', 'DEVOTO', 'EXPLORADOR', 'MISTERIOSO', 'INTREPIDO', name='archetypetype'), nullable=True),
    sa.Column('seductor_points', sa.Integer(), nullable=True),
    sa.Column('observer_points', sa.Integer(), nullable=True),
    sa.Column('devoto_points', sa.Integer(), nullable=True),
    sa.Column('explorador_points', sa.Integer(), nullable=True),
    sa.Column('misterioso_points', sa.Integer(), nullable=True),
    sa.Column('intrepido_points', sa.Integer(), nullable=True),
    sa.Column('visited_nodes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_interaction', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_chapter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_node_id'], ['story_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_story_progress_id'), 'user_story_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_story_progress_user_id'), 'user_story_progress', ['user_id'], unique=False)
    op.create_table('broadcast_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcast_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('reaction_emoji_id', sa.Integer(), nullable=False),
    sa.Column('besitos_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcast_messages.id'], ),
    sa.ForeignKeyConstraint(['reaction_emoji_id'], ['reaction_emojis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_reactions_broadcast_id'), 'broadcast_reactions', ['broadcast_id'], unique=False)
    op.create_index(op.f('ix_broadcast_reactions_id'), 'broadcast_reactions', ['id'], unique=False)
    op.create_index(op.f('ix_broadcast_reactions_user_id'), 'broadcast_reactions', ['user_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['store_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.create_index(op.f('ix_cart_items_user_id'), 'cart_items', ['user_id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mission_type', sa.Enum('REACTION_COUNT', 'DAILY_GIFT_STREAK', 'DAILY_GIFT_TOTAL', 'STORE_PURCHASE', 'VIP_ACTIVE', name='missiontype'), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Enum('ONE_TIME', 'RECURRING', name='missionfrequency'), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reward_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['store_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_table('promotion_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ATTENDED', 'BLOCKED', name='intereststatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('attended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attended_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'promotion_id', name='uq_user_promotion_interest')
    )
    op.create_index(op.f('ix_promotion_interests_id'), 'promotion_interests', ['id'], unique=False)
    op.create_index(op.f('ix_promotion_interests_user_id'), 'promotion_interests', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('user_story_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reward_delivered', sa.Boolean(), nullable=True),
    sa.Column('reward_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['story_achievements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_story_achievements_id'), 'user_story_achievements', ['id'], unique=False)
    op.create_index(op.f('ix_user_story_achievements_user_id'), 'user_story_achievements', ['user_id'], unique=False)
    op.create_table('user_mission_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_mission_progress_id'), 'user_mission_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_mission_progress_mission_id'), 'user_mission_progress', ['mission_id'], unique=False)
    op.create_index(op.f('ix_user_mission_progress_user_id'), 'user_mission_progress', ['user_id'], unique=False)
    op.create_table('user_reward_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_reward_history_id'), 'user_reward_history', ['id'], unique=False)
    op.create_index(op.f('ix_user_reward_history_user_id'), 'user_reward_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_reward_history_user_id'), table_name='user_reward_history')
    op.drop_index(op.f('ix_user_reward_history_id'), table_name='user_reward_history')
    op.drop_table('user_reward_history')
    op.drop_index(op.f('ix_user_mission_progress_user_id'), table_name='user_mission_progress')
    op.drop_index(op.f('ix_user_mission_progress_mission_id'), table_name='user_mission_progress')
    op.drop_index(op.f('ix_user_mission_progress_id'), table_name='user_mission_progress')
    op.drop_table('user_mission_progress')
    op.drop_index(op.f('ix_user_story_achievements_user_id'), table_name='user_story_achievements')
    op.drop_index(op.f('ix_user_story_achievements_id'), table_name='user_story_achievements')
    op.drop_table('user_story_achievements')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_promotion_interests_user_id'), table_name='promotion_interests')
    op.drop_index(op.f('ix_promotion_interests_id'), table_name='promotion_interests')
    op.drop_table('promotion_interests')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_cart_items_user_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_broadcast_reactions_user_id'), table_name='broadcast_reactions')
    op.drop_index(op.f('ix_broadcast_reactions_id'), table_name='broadcast_reactions')
    op.drop_index(op.f('ix_broadcast_reactions_broadcast_id'), table_name='broadcast_reactions')
    op.drop_table('broadcast_reactions')
    op.drop_index(op.f('ix_user_story_progress_user_id'), table_name='user_story_progress')
    op.drop_index(op.f('ix_user_story_progress_id'), table_name='user_story_progress')
    op.drop_table('user_story_progress')
    op.drop_index(op.f('ix_tokens_token_code'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_story_choices_id'), table_name='story_choices')
    op.drop_table('story_choices')
    op.drop_index(op.f('ix_story_achievements_id'), table_name='story_achievements')
    op.drop_table('story_achievements')
    op.drop_index(op.f('ix_store_products_id'), table_name='store_products')
    op.drop_table('store_products')
    op.drop_index(op.f('ix_rewards_id'), table_name='rewards')
    op.drop_table('rewards')
    op.drop_index(op.f('ix_promotions_id'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_pending_requests_user_id'), table_name='pending_requests')
    op.drop_index(op.f('ix_pending_requests_id'), table_name='pending_requests')
    op.drop_table('pending_requests')
    op.drop_index(op.f('ix_package_files_package_id'), table_name='package_files')
    op.drop_index(op.f('ix_package_files_id'), table_name='package_files')
    op.drop_table('package_files')
    op.drop_index(op.f('ix_broadcast_messages_message_id'), table_name='broadcast_messages')
    op.drop_index(op.f('ix_broadcast_messages_id'), table_name='broadcast_messages')
    op.drop_table('broadcast_messages')
    op.drop_index(op.f('ix_besito_transactions_user_id'), table_name='besito_transactions')
    op.drop_index(op.f('ix_besito_transactions_id'), table_name='besito_transactions')
    op.drop_table('besito_transactions')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tariffs_id'), table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_index(op.f('ix_story_nodes_id'), table_name='story_nodes')
    op.drop_table('story_nodes')
    op.drop_index(op.f('ix_reaction_emojis_id'), table_name='reaction_emojis')
    op.drop_table('reaction_emojis')
    op.drop_index(op.f('ix_packages_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_daily_gift_config_id'), table_name='daily_gift_config')
    op.drop_table('daily_gift_config')
    op.drop_index(op.f('ix_daily_gift_claims_user_id'), table_name='daily_gift_claims')
    op.drop_index(op.f('ix_daily_gift_claims_id'), table_name='daily_gift_claims')
    op.drop_table('daily_gift_claims')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_channel_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_blocked_promotion_users_user_id'), table_name='blocked_promotion_users')
    op.drop_index(op.f('ix_blocked_promotion_users_id'), table_name='blocked_promotion_users')
    op.drop_table('blocked_promotion_users')
    op.drop_index(op.f('ix_besito_balances_user_id'), table_name='besito_balances')
    op.drop_index(op.f('ix_besito_balances_id'), table_name='besito_balances')
    op.drop_table('besito_balances')
    op.drop_index(op.f('ix_archetypes_id'), table_name='archetypes')
    op.drop_table('archetypes')
    # ### end Alembic commands ###
